apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:   
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      labels: 
        app: web
    spec:
      initContainers:
        - name: web-init
          image: busybox:1.32
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
          volumeMounts:
            - name: app
              mountPath: /app
      containers:
        - name: web
          image: torwaldmalafsen/otus_kuber_nginx:1.0.9
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
          livenessProbe:
              tcpSocket: { port: 8000 }
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          emptyDir: { }


















