apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  selector:
    app: nginx-app
  type: ClusterIP
  ports:
    - name: nginx-app
      protocol: TCP
      port: 80
      targetPort: 8080